version: '3'

services:
  node:
    container_name: test_container
    restart: always
    ports:
      - '8080:8080'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./public-html/src/index.html:/var/www/html/src/index.html

# https://medium.com/@zhao.li/how-to-understand-working-with-files-in-containers-using-docker-compose-6d8e68ed790b
